version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: campaign_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./campaign-backend
    container_name: campaign_backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./campaign-backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./campaign-frontend
    container_name: campaign_frontend
    restart: always
    ports:
      - "8080:80"

volumes:
  mongo_data:
